### ISSUE TITLE
Reuse process-compose if available

### ISSUE THREAD

**Issue by diegobernardes** [jetify-com/devbox#1999]
### What problem are you trying to solve?

I'm installing Devbox on GitHub Actions using the following snippet:
```yml
- name: Install devbox
  uses: jetify-com/devbox-install-action@v0.9.0
  with:
    enable-cache: true
```

It works alright and everything is installed and cached, the run after the cache is quite fast, 40 seconds or so to install everything and restore the cache. But not everything is cached and the issue happens when I try to spin up the dependencies to run my tests. Every time it installs `process-compose` and that process takes quite some time because there is no cache. I tried to add `process-compose` to my list of packages on Devbox, but it did not worked, even listed there, Devbox tries to download it every time.

### What solution would you like?

If `process-compose` is at the `packages` list of Devbox it should be reused.

**Comment by jay-aye-see-kay** [comment]
I just ran into this issue today too, would be fantastic to have an option like this that pre-installed and cached process-compose in CI jobs where it was used.

```yaml
- name: Install devbox
  uses: jetify-com/devbox-install-action@v0.9.0
  with:
    enable-cache: true
    install-process-compose: true
```
