### ISSUE TITLE
Prompt (starship) looks broken in zsh and in fish

### ISSUE THREAD

**Issue by niklasravnsborg** [jetify-com/devbox#2041]
### What happened?

<img width="1512" alt="Screenshot 2024-05-08 at 22 18 40" src="https://github.com/jetify-com/devbox/assets/6717303/4246831c-8f18-487e-8b5b-333347543093">

### Steps to reproduce

1. Install [Starship](https://starship.rs/) prompt (I installed it via [home-manager](https://nix-community.github.io/home-manager/options.xhtml#opt-programs.starship.enable)).
2. Run `devbox init` in  a project
3. Run `devbox shell`

### Command

shell

### devbox.json

```jsonc
{
  "$schema":  "https://raw.githubusercontent.com/jetify-com/devbox/0.10.5/.schema/devbox.schema.json",
  "packages": ["bun@latest"],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

### Devbox version

0.10.5

### Nix version

nix (Nix) 2.18.2

### What system does this bug occur on?

macOS (Apple Silicon)

**Comment by bohrium2b** [comment]
This is likely caused by the devbox prompt. You can turn it off (allegedly; I haven't been able to make it work) by setting `DEVBOX_NO_PROMPT` to true. On fish, you can do it using `set -gx DEVBOX_NO_PROMPT true`.

**Comment by MacroPower** [comment]
I was able to make it work with fish by using lowercase:

`set -gx devbox_no_prompt true`

**Comment by maulik13** [comment]
I am in the same boat, not sure what I need to do in zsh to not have devbox as a prefix for my prompt which disrupts the starship prompt.

**Comment by maulik13** [comment]
I managed to solve this by setting the environment variable `DEVBOX_NO_PROMPT=0` in my zshrc

And with the following starship custom element:

```toml
[custom.devbox]
description = "Shows an indicator when inside a Devbox shell"
format = "[  devbox]($style)"
style = "fg:gold bg:overlay"
when = "env | grep -E '^DEVBOX_SHELL_ENABLED='"
ignore_timeout = true
```
