### ISSUE TITLE
feat: exit_hook

### ISSUE THREAD

**Issue by pythoninthegrass** [jetify-com/devbox#2362]
### What problem are you trying to solve?

`init_hook`s are cool. I'd like `exit_hook`s that do the opposite. For instance, I'm always starting up an ephemeral redis container for ansible facts that only lasts during my project work. 

You already implemented process-compose for [redis](https://www.jetify.com/docs/devbox/devbox_examples/databases/redis/) (and other services!), which precludes a docker step. Now turning it off automatically would complete the loop.

### What solution would you like?

With `exit_hook`s, in addition to returning to the original shell, it would have some kind of de-scaffolding.

If we keep it general, `exit_hook`s could act like bash traps or python's try/except/**finally** blocks.

Essentially, the workflow would resemble:

```json
{
  "packages": [
    "redis@latest"
  ],
  "env": {
    "REDIS_PORT":      "6379",
    "REDIS_CONF":      "./devbox.d/redis/redis.conf"
  },
  "shell": {
    "init_hook": [
      "devbox services start redis"
    ],
    "exit_hook": [
      "devbox services stop redis"
    ],
    "scripts": {}
  }
}
```

### Alternatives you've considered

Didn't find anything in my cursory search.

However, it wouldn't take a lot of effort to write a shell script or python script to do the same thing. But that defeats the utility of devbox and requires bespoke solutions.

**Comment by pythoninthegrass** [comment]
Would also solve #2354.

Novel use of a [script](https://github.com/jetify-com/devbox/issues/2354#issuecomment-2413120731) though.

**Comment by DerArkeN** [comment]
Besides stopping running services (which imo should happen when the shell dies anyway), is there an actual use case for exit_hooks?

As a workaround you could use your mentioned traps in the init_hooks like the following:
```json
{
    "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/0.13.5/.schema/devbox.schema.json",
    "packages": [],
    "shell": {
      "init_hook": [
        "echo 'Welcome to devbox!'",
        "trap 'echo Goodbye from devbox!' EXIT"
      ],
    }
}
```
This will result in the following:
![image](https://github.com/user-attachments/assets/fd20ec25-6b4d-40a5-9a41-b21879b602f6)

**Comment by pythoninthegrass** [comment]
Appreciate the response @DerArkeN !

This works
```json
"shell": {
    "init_hook": [
      ". $VENV_DIR/bin/activate",
      "uv pip install -r requirements.txt",
      "[ $(uname -s ) = 'Darwin' ] && export ANSIBLE_BECOME_PASS=$(askpass --sudo)",
      "devbox services start redis --quiet",
      "trap 'devbox services stop redis --quiet' EXIT"
    ],
```

but it's kludgey. (Side note: had no idea traps worked outside of shell scripts! Unless ofc this is converted into one haha)

I can work around it with a taskfile

```yaml
version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

env:
  REDIS_PORT: "6379"
  REDIS_CONF: "./devbox.d/redis/redis.conf"

tasks:
  start:
    desc: "Start Redis server"
    cmds:
      - devbox services start redis --quiet
    silent: true

  restart:
    desc: "Restart Redis server"
    cmds:
      - devbox services restart redis --quiet
    silent: true

  stop:
    desc: "Stop Redis server"
    cmds:
      - devbox services stop redis --quiet
    silent: true
```

then

```json
"shell": {
    "init_hook": [
      ". $VENV_DIR/bin/activate",
      "uv pip install -r requirements.txt",
      "[ $(uname -s ) = 'Darwin' ] && export ANSIBLE_BECOME_PASS=$(askpass --sudo)",
      "task redis:start",
      "trap 'task redis:stop' EXIT"
    ],
```

but a separation of concerns would be a more streamlined approach.

Services _do not_ die with the shell fwiw. I agree that if they did, exit hooks wouldn't be as applicable to `process-compose` managed services. For everything else, still think exit hooks would be handy.
