### ISSUE TITLE
Allow for an official plugin to allow for customizing the devbox manifest file.

### ISSUE THREAD

**Issue by CourteousCoder** [jetify-com/devbox#2621]
## Summary 
Relate to #1590, #2169, #2602, #2480
 
There are a lot of requests for allowing support for different configuration languages for `devbox.json`, such as JSONC,`YAML, TOML, etc. But Devbox already includes a plugin API that allows for adding custom options to `devbox.json`

## This might already be possible

I think we might already have a feasible and practical way to implement this with the existing plugin API. I have not verified this.

Based on [the current plugin API](https://www.jetify.com/docs/devbox/guides/creating_plugins/#plugin-design) ([Wayback Machine archive](https://web.archive.org/web/20250601222100/https://www.jetify.com/docs/devbox/guides/creating_plugins/#plugin-design)), I don't see why a plugin couldn't adhere to the devbox schema and then utilize its own config file (e.g. a `plugin:yaml` could manage to utilize a `devbox.yaml` and implement the same schema as `devbox.json`, but in yaml.

The only issue I can think of is the corner case where another external plugin reads to or writes from `devbox.json` directly. But if this is a problem, then there is probably a some kind of hacky workaround for it too (e.g. another plugin to sync manifest files or something like that)

### What solution would you like?

Add support for plugins to hook into whatever modules handle interact with `devbox.json` directly. Then we could achieve something like this. 
`devbox.json` directly. 

## In `devbox.json`
```jsonc
{
 "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/0.14.2/.schema/devbox.schema.json",

  "include": [
      // or perhaps "plugin:devbox-yaml", or even "plugin:yaml" for brevity
      // or for whatever kind of config language support you want.
      // "plugin:toml",
      // "plugin:jsonc",
      // "plugin:dhall",
      // ...
      "plugin:manifest-yaml",
  ]
}
```

## In `devbox.d/manifest-yaml/devbox.yaml`

(or however your plugin decides to locate the yaml file)

```yaml
{
  # These are comments made with `#` because its yaml not jsonc
  "name": "",
  "version": "",
  "description": "",
  "packages": [], # or {} of packages
  "env": { "<key>": "<value>" },
  "create_files": {},
  # "<destination>": "<source>"
  "shell": {
      "init_hook": [],
      # "<bash commands>"
      "scripts": { "<key>": "<value>" },
    },
  "include": ["<path_to_plugin>"],
}

```

which could then be refactored to a `devbox.yaml` like this
```yaml
name: ExampleDevboxYaml# name of your devbox shell
version: 0.0.1 # your project version
description: This is an example devbox configured with yaml
packages:
  - someNixPkgs
  - github:someFlake
  - fooPackages.bar@version^out,dev,
env:
  SOME_ENV_VAR: someValue
create_files:
  "./destination/of/file": ./source/of/file
shell:
  init_hook:
    - echo 'some bash commands'
    - echo 'or a multiline string justl like you would see with ci programs e.g. github actions'
scripts:
  someKey: someValue
include:
  - ./path/to/plugin

```
